---
include:
  - board: cosmos_lemon_wireless
    shield: pedantric1_left
    snippet: zmk-usb-logging;studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: cosmos_lemon_wireless
    shield: pedantric1_right
  - board: seeeduino_xiao_ble
    shield: pedadantic1_dongle prospector_adapter